rudderlabs/rudder-sdk-flutter

- CHANGELOG.md
- pubspec.yaml
> Bumped Version to 1.0.1-beta1

- README.md
- example/pubspec.yaml
- ios/Classes/RudderSdkFlutterPlugin.h
- pubspec.yaml
> Fixed Module Imports in native iOS of Flutter SDK

- README.md
- pubspec.yaml
> Bumped version to 1.0.1

- CHANGELOG.md
- README.md
- android/src/main/java/com/rudderstack/sdk/flutter/RudderSdkFlutterPlugin.java
- example/lib/main.dart
- ios/Classes/RudderSdkFlutterPlugin.m
- lib/RudderClient.dart
- lib/RudderConfig.dart
- lib/Utils.dart
- pubspec.yaml
> Exporting Context from Native to Flutter

- CHANGELOG.md
- README.md
- android/src/main/java/com/rudderstack/sdk/flutter/RudderSdkFlutterPlugin.java
- ios/Classes/RudderSdkFlutterPlugin.m
- ios/rudder_sdk_flutter.podspec
- lib/RudderClient.dart
- pubspec.yaml
> GDPR Support for Flutter SDK

- README.md
> Changed SDK Version to 1.0.2 in Readme

- CHANGELOG.md
- README.md
- android/src/main/java/com/rudderstack/sdk/flutter/RudderSdkFlutterPlugin.java
- ios/Classes/RudderSdkFlutterPlugin.m
- ios/rudder_sdk_flutter.podspec
- lib/RudderClient.dart
- pubspec.yaml
> Revert back from gdpr for flutter sdk

- README.md
- android/src/main/java/com/rudderstack/sdk/flutter/ActivityLifeCycleHandler.java
- android/src/main/java/com/rudderstack/sdk/flutter/RudderSdkFlutterPlugin.java
- ios/Classes/RudderSdkFlutterPlugin.h
- ios/Classes/RudderSdkFlutterPlugin.m
- lib/RudderClient.dart
- pubspec.yaml
> Enhanced Track Life Cycle Events Support for Flutter SDK

- README.md
- android/build.gradle
- android/src/main/java/com/rudderstack/sdk/flutter/RudderSdkFlutterPlugin.java
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- ios/Classes/RudderSdkFlutterPlugin.m
- ios/rudder_sdk_flutter.podspec
- lib/RudderClient.dart
- pubspec.yaml
> Added GDPR Support for Flutter SDK after Enhancement

- README.md
- android/build.gradle
- ios/rudder_sdk_flutter.podspec
- pubspec.yaml
> Updated SDK Versions

- android/build.gradle
- ios/rudder_sdk_flutter.podspec
- pubspec.yaml
> Version update for iOS & Android
> [Release] Version 1.0.8

- rudder_plugin/CHANGELOG.md
- rudder_plugin/README.md
- rudder_plugin/example/pubspec.yaml
- rudder_plugin/pubspec.yaml
- rudder_plugin_android/CHANGELOG.md
- rudder_plugin_android/README.md
- rudder_plugin_android/pubspec.yaml
- rudder_plugin_interface/CHANGELOG.md
- rudder_plugin_interface/README.md
- rudder_plugin_ios/CHANGELOG.md
- rudder_plugin_ios/README.md
- rudder_plugin_ios/pubspec.yaml
- rudder_plugin_web/CHANGELOG.md
- rudder_plugin_web/README.md
- rudder_plugin_web/pubspec.yaml
> updated versions

- integrations/rudder_integration_adjust_flutter/ios/rudder_integration_adjust_flutter.podspec
- integrations/rudder_integration_adjust_flutter/pubspec.yaml
- integrations/rudder_integration_amplitude_flutter/ios/rudder_integration_amplitude_flutter.podspec
- integrations/rudder_integration_amplitude_flutter/pubspec.yaml
- integrations/rudder_integration_appcenter_flutter/ios/rudder_integration_appcenter_flutter.podspec
- integrations/rudder_integration_appcenter_flutter/pubspec.yaml
- integrations/rudder_integration_braze_flutter/ios/rudder_integration_braze_flutter.podspec
- integrations/rudder_integration_braze_flutter/pubspec.yaml
- integrations/rudder_integration_firebase_flutter/ios/rudder_integration_firebase_flutter.podspec
- integrations/rudder_integration_firebase_flutter/pubspec.yaml
- integrations/rudder_integration_leanplum_flutter/ios/rudder_integration_leanplum_flutter.podspec
- integrations/rudder_integration_leanplum_flutter/pubspec.yaml
> Fixed issues in podspec files of the ios modules of Flutter Device Modes
> Fixed issues in podspec files of the ios modules of Flutter Device Modes

- rudder_plugin/example/ios/Flutter/AppFrameworkInfo.plist
- rudder_plugin/example/ios/Podfile
- rudder_plugin/example/ios/Podfile.lock
- rudder_plugin/example/ios/Runner.xcodeproj/project.pbxproj
- rudder_plugin/example/ios/Runner/Info.plist
> fix: Handled Storage Properties Unavailable issue for Leanplum iOS device mode
> fix: Handled Storage Properties Unavailable issue for Leanplum iOS device mode

- packages/integrations/rudder_integration_firebase_flutter/ios/rudder_integration_firebase_flutter.podspec
- packages/integrations/rudder_integration_firebase_flutter/pubspec.yaml
> Upgraded to Rudder-Firebase SDK 3.0.0
> feat: upgraded to Rudder-Firebase SDK 3.0.0

- melos.yaml
- packages/example/android/app/src/main/AndroidManifest.xml
- packages/example/ios/Podfile.lock
- packages/example/ios/Runner.xcodeproj/project.pbxproj
- packages/example/lib/home_screen.dart
- packages/example/pubspec.lock
- packages/example/web/index.html
- packages/plugins/rudder_plugin/pubspec.lock
- packages/plugins/rudder_plugin_android/android/build.gradle
- packages/plugins/rudder_plugin_interface/lib/src/models/rudder_config.dart
- packages/plugins/rudder_plugin_interface/test/src/models/rudder_config_test.dart
- packages/plugins/rudder_plugin_ios/ios/rudder_plugin_ios.podspec
- packages/plugins/rudder_plugin_web/lib/rudder_plugin_web.dart
- pubspec.lock
> minor updates in the ci and monorepo implementation
> chore(monorepo): minor updates in the ci and monorepo implementation

- .github/ISSUE_TEMPLATE/bug_report.md
- CODEOWNERS
> chore: add issue template for bug report

- .github/workflows/deploy-pubdev.yml
> ci: updated path of the pub.dev credentials with reference to macos runner
> ci: updated path of the pub.dev credentials with reference to macos runner

- packages/example/pubspec.lock
- packages/integrations/rudder_integration_adjust_flutter/pubspec.lock
- packages/integrations/rudder_integration_amplitude_flutter/pubspec.lock
- packages/integrations/rudder_integration_appcenter_flutter/pubspec.lock
- packages/integrations/rudder_integration_braze_flutter/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/pubspec.lock
- packages/integrations/rudder_integration_leanplum_flutter/pubspec.lock
- packages/plugins/rudder_plugin/pubspec.lock
- packages/plugins/rudder_plugin_android/pubspec.lock
- packages/plugins/rudder_plugin_ios/ios/Classes/RudderSdkFlutterPlugin.m
- packages/plugins/rudder_plugin_ios/pubspec.lock
- packages/plugins/rudder_plugin_web/pubspec.lock
- pubspec.lock
> fixed flutter engine hasn't started running issue
> Fix [#1]()
> fix: fixed flutter engine hasn't started running issue

- .github/workflows/deploy-pubdev.yml
- .github/workflows/publish-new-release.yml
> ci(monorepo): add manual deploy trigger, delete stray version tag

- .github/workflows/deploy-pubdev.yml
- .github/workflows/publish-new-release.yml
> ci(monorepo): add manual trigger in deploy action

- .github/workflows/deploy-pubdev.yml
- .github/workflows/housekeeping.yaml
> ci(monorepo): add --yes to melos publish

- packages/example/pubspec.lock
- packages/integrations/rudder_integration_adjust_flutter/pubspec.lock
- packages/integrations/rudder_integration_amplitude_flutter/pubspec.lock
- packages/integrations/rudder_integration_appcenter_flutter/pubspec.lock
- packages/integrations/rudder_integration_braze_flutter/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/pubspec.lock
- packages/integrations/rudder_integration_leanplum_flutter/pubspec.lock
- packages/plugins/rudder_plugin/pubspec.lock
- packages/plugins/rudder_plugin_android/pubspec.lock
- packages/plugins/rudder_plugin_interface/lib/src/utils.dart
- packages/plugins/rudder_plugin_interface/pubspec.lock
- packages/plugins/rudder_plugin_interface/pubspec.yaml
- packages/plugins/rudder_plugin_interface/test/src/models/utils_test.dart
- packages/plugins/rudder_plugin_ios/pubspec.lock
- packages/plugins/rudder_plugin_web/pubspec.lock
- pubspec.lock
- pubspec.yaml
> replace usage of intl package with custom logic
> Fix [#93]()
> fix: replace usage of intl package with custom logic

- .github/workflows/deploy-pubdev.yml
- .github/workflows/housekeeping.yaml
- .github/workflows/publish-new-release.yml
- melos.yaml
> fixed ci issues in publishing to pub.dev
> ci: fixed ci issues in publishing to pub.dev

- packages/example/pubspec.lock
- packages/integrations/rudder_integration_adjust_flutter/pubspec.lock
- packages/integrations/rudder_integration_amplitude_flutter/pubspec.lock
- packages/integrations/rudder_integration_appcenter_flutter/pubspec.lock
- packages/integrations/rudder_integration_braze_flutter/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/pubspec.lock
- packages/integrations/rudder_integration_leanplum_flutter/pubspec.lock
- packages/plugins/rudder_plugin/pubspec.lock
- packages/plugins/rudder_plugin/pubspec.yaml
- packages/plugins/rudder_plugin_android/pubspec.lock
- packages/plugins/rudder_plugin_ios/pubspec.lock
- packages/plugins/rudder_plugin_web/pubspec.lock
- packages/plugins/rudder_plugin_web/pubspec.yaml
- pubspec.lock
> fix: removed usage of intl across multiple packages

- CODEOWNERS
- packages/plugins/rudder_plugin/README.md
added list of features in the core package Readme file
> feat: added list of features in the core package

- packages/plugins/rudder_plugin_web/lib/rudder_plugin_web.dart
fixed in-valid method call in web plugin due to merge issues
> fix: fixed in-valid method call in web plugin due to merge issues

- CHANGELOG.md
- packages/example/pubspec.yaml
- packages/integrations/rudder_integration_adjust_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_adjust_flutter/pubspec.yaml
- packages/integrations/rudder_integration_amplitude_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_amplitude_flutter/pubspec.yaml
- packages/integrations/rudder_integration_appcenter_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_appcenter_flutter/pubspec.yaml
- packages/integrations/rudder_integration_appsflyer_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_appsflyer_flutter/pubspec.yaml
- packages/integrations/rudder_integration_braze_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_braze_flutter/pubspec.yaml
- packages/integrations/rudder_integration_firebase_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_firebase_flutter/pubspec.yaml
- packages/integrations/rudder_integration_leanplum_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_leanplum_flutter/pubspec.yaml
- packages/plugins/rudder_plugin/CHANGELOG.md
- packages/plugins/rudder_plugin/pubspec.yaml
- packages/plugins/rudder_plugin_web/CHANGELOG.md
- packages/plugins/rudder_plugin_web/pubspec.yaml
- pubspec.yaml
- sonar-project.properties
> chore(release): pulling release/3.2.1 into main

- packages/example/ios/Podfile.lock
- packages/example/pubspec.lock
- packages/example/pubspec.yaml
- packages/integrations/rudder_integration_adjust_flutter/pubspec.lock
- packages/integrations/rudder_integration_amplitude_flutter/pubspec.lock
- packages/integrations/rudder_integration_appcenter_flutter/pubspec.lock
- packages/integrations/rudder_integration_braze_flutter/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/pubspec.lock
- packages/integrations/rudder_integration_leanplum_flutter/pubspec.lock
- packages/plugins/rudder_plugin/pubspec.lock
- packages/plugins/rudder_plugin_android/android/build.gradle
- packages/plugins/rudder_plugin_android/pubspec.lock
- packages/plugins/rudder_plugin_ios/pubspec.lock
- packages/plugins/rudder_plugin_web/pubspec.lock
- pubspec.lock
* updated the android SDK version to fix the invalid JSON issue while sending batches to the dataplane.
- [] "Ready for review" label attached to the PR and reviewers mentioned in a comment
> fix: updated the android sdk version to fix the invalid json issue

- LICENSE
- LICENSE.md
> Updates open source software license
> chore: update license to ELv2

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/draft-new-release.yml
- .github/workflows/publish-new-release.yml
- CODEOWNERS
- Update codeowners.
- Updated assignee at bug_report.
- Updated PR reviewer at draft-new-release and publish-new-release.
> Fix [#1]()
> chore: update codeowners files

- CHANGELOG.md
- packages/example/CHANGELOG.md
- packages/example/ios/Podfile
- packages/example/ios/Podfile.lock
- packages/example/ios/Runner.xcodeproj/project.pbxproj
- packages/example/pubspec.lock
- packages/example/pubspec.yaml
- packages/integrations/rudder_integration_kochava_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_kochava_flutter/ios/rudder_integration_kochava_flutter.podspec
- packages/integrations/rudder_integration_kochava_flutter/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- sonar-project.properties
> chore(release): pulling release/3.8.2 into main

- packages/example/ios/Podfile.lock
- packages/example/ios/Runner.xcodeproj/project.pbxproj
- packages/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/example/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/android/build.gradle
- packages/integrations/rudder_integration_firebase_flutter/ios/rudder_integration_firebase_flutter.podspec
- packages/integrations/rudder_integration_firebase_flutter/pubspec.lock
- In this PR, we update the Rudder-Firebase Android and iOS SDKs to the latest version.
> Fix [#1]()
> feat: update firebase SDKs to the latest version

- CHANGELOG.md
- packages/example/CHANGELOG.md
- packages/example/ios/Podfile.lock
- packages/example/ios/Runner.xcodeproj/project.pbxproj
- packages/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/example/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_firebase_flutter/android/build.gradle
- packages/integrations/rudder_integration_firebase_flutter/ios/rudder_integration_firebase_flutter.podspec
- packages/integrations/rudder_integration_firebase_flutter/pubspec.lock
- packages/integrations/rudder_integration_firebase_flutter/pubspec.yaml
- pubspec.yaml
- sonar-project.properties
> chore(release): pulling release/4.1.0 into main

- .github/workflows/build-and-quality-checks.yml
- .github/workflows/deploy-pubdev.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/housekeeping.yaml
- .github/workflows/notion-pr-sync.yml
- .github/workflows/publish-new-release.yml
- .github/workflows/test.yml
- Updated GitHub Action to use commit SHA's.
> Fix [#1]()
> ci: use shas for external github actions

- packages/plugins/rudder_plugin_db_encryption/example/lib/main.dart
- packages/plugins/rudder_plugin_db_encryption/lib/rudder_plugin_db_encryption.dart
- Added example app.
- Fixed linting issues.
> Fix [#1]()
> chore: improve score by adding example

- .github/workflows/deploy-pubdev.yml
- .github/workflows/publish-new-release.yml
- CHANGELOG.md
- example/pubspec.lock
- packages/plugins/rudder_plugin_db_encryption/CHANGELOG.md
- packages/plugins/rudder_plugin_db_encryption/lib/rudder_plugin_db_encryption.dart
- packages/plugins/rudder_plugin_db_encryption/pubspec.yaml
- pubspec.yaml
- sonar-project.properties
> chore(release): pull release/4.5.1 into main

- CHANGELOG.md
- packages/integrations/rudder_integration_appsflyer_flutter/CHANGELOG.md
- packages/integrations/rudder_integration_appsflyer_flutter/ios/rudder_integration_appsflyer_flutter.podspec
- packages/integrations/rudder_integration_appsflyer_flutter/pubspec.yaml
- pubspec.yaml
- sonar-project.properties
> chore(release): pull release/4.7.0 into main
